######################################################################
# Automatically generated by qmake (3.0) Sat Mar 29 19:38:17 2014
######################################################################

TEMPLATE = app
TARGET = 3dEngine
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
QT += widgets